---
title: "Dissertation Project Analysis"
author: "Joshua Travis Hiepler"
date: "11/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```
'"||||
```{r}
library(tidyverse)
library(pwr)
library(esc)
library(jtools)
```

```{r}
source <- read_csv("results_final.csv")
source_long <- pivot_longer(source, "NV-NV":"V-NV+V", names_to = "condition", values_to = "accuracy")
source_long$condition <- factor(source_long$condition,levels = c("NV-NV", "V-V", "NV-V", "V-NV", "NV-NV+V", "V-NV+V", "NV+V-NV", "NV+V-V"))
head(source_long, 10)
```
```{r}
#Descriptives of all conditions
descriptives <- group_by(source_long, condition) %>%
  summarise(mean = mean(accuracy), sd = sd(accuracy)) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2))

ggplot(source_long, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("red","gold","green","orange","turquoise","sky blue","purple","dark green")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent) 

#Power Analysis
pwr.t.test(d = 0.2, sig.level = .05, power = 0.8, type = "two.sample", alternative = "greater")
pwr.t.test(d = 0.2, sig.level = .05, n = 500, type = "two.sample", alternative = "greater")
0.05/5
```
```{r}
#NV-NV and V-V

#Create new df with only NV-NV and V-V data
H1_df <- filter(source_long, condition %in% c("NV-NV", "V-V"))

#Boxplot of NV-V and V-V
ggplot(H1_df, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("red","gold")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent) 

#Descriptives
H1_desc <- filter(descriptives, condition %in% c("NV-NV","V-V")) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2), difference = round(max(mean_percent)-min(mean_percent), digits = 2))

#Perform independent t-test
t.test(accuracy ~ condition, data = H1_df, alternative = "greater", paired = FALSE)

#Calculate effect size
esc_t(t = 12.743, grp1n = 500, grp2n = 500, es.type="g")
```
```{r}
#NV-V and V-V

#Create new df with only NV-V and V-V data
H2_df <- filter(source_long, condition %in% c("NV-V", "V-V"))

#Boxplot of NV-V and V-V
ggplot(H2_df, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("gold","green")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent)

#Descriptives
H2_desc <- filter(descriptives, condition %in% c("NV-V","V-V")) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2), difference = round(max(mean_percent)-min(mean_percent), digits = 2))

#Perform paired t-test
t.test(accuracy ~ condition, data = H2_df, alternative = "greater", paired = FALSE)

#Calculate effect size
esc_t(t = 123.13, grp1n = 500, grp2n = 500, es.type="g")
```
```{r}
#NV+V-NV vs NV+V-V

#Create new df with only NV+V-NV and NV+V-V data
E1_df <- filter(source_long, condition %in% c("NV+V-NV", "NV+V-V"))

#Boxplot of NV+V-NV and NV+V-V
ggplot(E1_df, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("purple","dark green")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent)

#Descriptives
E1_desc <- filter(descriptives, condition %in% c("NV+V-NV","NV+V-V")) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2), difference = round(max(mean_percent)-min(mean_percent), digits = 2))

#Perform paired t-test
t.test(accuracy ~ condition, data = E1_df, paired = FALSE)

#Calculate effect size
esc_t(t = 17.141, grp1n = 500, grp2n = 500, es.type="g")
```
```{r}
#V-NV+V vs NV-NV+V

#Create new df with only NV-NV+V and V-NV+V data
E2_df <- filter(source_long, condition %in% c("NV-NV+V", "V-NV+V"))

#Boxplot of NV-NV+V and V-NV+V
ggplot(E2_df, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("turquoise","sky blue")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent)

#Descriptives
E2_desc <- filter(descriptives, condition %in% c("NV-NV+V","V-NV+V")) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2), difference = round(max(mean_percent)-min(mean_percent), digits = 2))

#Perform paired t-test
t.test(accuracy ~ condition, data = E2_df, paired = FALSE)

#Calculate effect size
esc_t(t = -13.84, grp1n = 500, grp2n = 500, es.type="g")
```
```{r}
#V-NV vs NV-NV

#Create new df with only V-NV and NV-NV data
E3_df <- filter(source_long, condition %in% c("V-NV", "NV-NV"))

#Boxplot of V-NV and NV-NV
ggplot(E3_df, aes(x = condition, y = accuracy, fill = condition)) + geom_boxplot(width=0.6) + geom_violin(trim=FALSE, width=0.8, alpha=0.5) + scale_fill_manual(values=c("red","orange")) + theme_apa() + labs(x = "Model Condition", y = "Identification Accuracy") + scale_y_continuous(breaks = seq(0, 1, .05), labels = scales::percent)

#Descriptives
E3_desc <- filter(descriptives, condition %in% c("V-NV","NV-NV")) %>%
  mutate(mean_percent = round(mean * 100, digits = 2), sd_percent = round(sd * 100, digits = 2), difference = round(max(mean_percent)-min(mean_percent), digits = 2))

#Perform paired t-test
t.test(accuracy ~ condition, data = E3_df, paired = FALSE)

#Calculate effect size
esc_t(t = 117.04, grp1n = 500, grp2n = 500, es.type="g")
```


